name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        id: timestamp
        run: echo "::set-output name=value::$(/bin/date -u "+%Y%m%d")"
      - name: Restore the previous run result
        uses: actions/cache@v2
        with:
          path: prev_result
          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.value }}
          restore-keys: ${{ github.run_id }}-${{ github.job }}-
      - name: Parse previous result
        id: prev_result
        run: cat prev_result 2>/dev/null || echo 'no result'

      - name: Checkout
        if: steps.prev_result.outputs.value != 'success'
        uses: actions/checkout@v2

      - name: Sleep
        if: steps.prev_result.outputs.value != 'success'
        run: |
          echo "${{ github.sha }}"
          sleep 15

      - name: Remember result
        if: ${{ always() }}
        run: echo "::set-output name=value::${{ job.status }}" > prev_result
  test-fail:
    if: 'false'
    needs: ['build-docker']
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        id: timestamp
        run: echo "::set-output name=value::$(timestamp +%s)"
      - name: Restore the previous run result
        uses: actions/cache@v2
        with:
          path: prev_result
          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.value }}
          restore-keys: ${{ github.run_id }}-${{ github.job }}-
      - name: Parse previous result
        id: prev_result
        run: cat prev_result 2>/dev/null || echo 'no result'

      - name: Checkout
        if: steps.prev_result.outputs.value != 'success'
        uses: actions/checkout@v2

      - name: Error
        if: steps.prev_result.outputs.value != 'success'
        run: |
          error

      - name: Remember result
        if: ${{ always() }}
        run: echo "::set-output name=value::${{ job.status }}" > prev_result
  test-success:
    needs: ['test-fail']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '${{ github.sha }}'
      - name: Sleep
        id: sleep
        run: |
          echo "${{ github.sha }}"
          sleep 15
