name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sleep
        id: sleep
        run: |
          sleep 15
