name: Build

on:
  push:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - id: timestamp
        run: echo "::set-output name=timestamp::$(timestamp +%s)"
      - name: Restore the previous run result
        uses: actions/cache@v2
        with:
          path: |
            run_result
          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ github.run_id }}-${{ github.job }}-
      - id: run_result
        run: cat run_result 2>/dev/null || echo 'default'
      - uses: actions/checkout@v2
        if: steps.run_result.outputs.run_result != 'success'
      - run: echo "::set-output name=run_result::success" > run_result
  build-docker:
    needs: ['prepare']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sleep
        id: sleep
        run: |
          echo "${{ github.sha }}"
          sleep 15
  test-fail:
    needs: ['build-docker']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Error
        id: error
        run: |
          error
  test-success:
    needs: ['test-fail']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '${{ github.sha }}'
      - name: Sleep
        id: sleep
        run: |
          echo "${{ github.sha }}"
          sleep 15
