name: Build

on:
  push:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - id: timestamp
        run: echo "::set-output name=timestamp::$(timestamp +%s)"
      - name: Restore the previous success jobs
        uses: actions/cache@v2
        with:
          path: |
            success_jobs
          key: ${{ github.run_id }}-${{ steps.timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ github.run_id }}-
      - id: success_jobs
        run: cat success_jobs 2>/dev/null || echo ''
    outputs:
      success_jobs: ${{ steps.success_jobs.outputs }}

  build-docker:
    needs: ['prepare']
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ needs.prepare.outputs.success_jobs }}"
          echo "${{ needs.prepare.outputs.success_jobs.build_docker }}"
          echo "${{ needs.prepare.outputs.success_jobs['build-docker'] }}"
      - uses: actions/checkout@v2
      - name: Sleep
        id: sleep
        run: |
          echo "${{ github.sha }}"
          sleep 15
      - run: |
          echo "::set-output name=build_docker::success }}" > success_jobs
          echo "::set-output name=build-docker::success }}" > success_jobs
  test-fail:
    needs: ['build-docker']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Error
        id: error
        run: |
          error
  test-success:
    needs: ['test-fail']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '${{ github.sha }}'
      - name: Sleep
        id: sleep
        run: |
          echo "${{ github.sha }}"
          sleep 15
