name: Test Fail 2

on:
#  workflow_run:
#    workflows: ["Test Fail"]
#    types:
#      - completed
  workflow_dispatch:

jobs:
  test-fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Error
        id: error
        run: |
          error
