name: Test Success 2

on:
  workflow_run:
    workflows: ["Test Success"]
    types:
      - completed
  workflow_dispatch:

jobs:
  test-success:
    runs-on: ubuntu-latest
    steps:
      -
        name: Sleep
        id: sleep
        run: |
          sleep 15
