name: Test Fail

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  workflow_dispatch:

jobs:
  test-fail:
    runs-on: ubuntu-latest
    steps:
      -
        name: Error
        id: error
        run: |
          error
